---
title: "第二章  商业银行资本管理"
author: "Qiufei"
date: "2/6/2017"
output:
  ioslides_presentation: 
    logo: wanli.png
    widescreen: true
    keep_md: yes
---


# 商业银行资本管理 #

## 商业银行是经营风险的机构 ##
金融机构的核心竞争力是管理风险的能力。商业银行面临以下风险：

1. 信用风险：别人不支付给我
2. 流动性风险：我无力支付给别人
3. 利率风险
4. 汇率风险
5. 操作风险

<div class="notes">

这里可以做**笔记**。

</div>


## 商业银行资本的性质 ##

商业银行资本（净值）是商业抵偿风险的最后一道防线。

## 银行资本的作用 ##
银行资本的关键作用是：
1. 吸收意外损失
2. 消除银行的不稳定因素
银行保持充足的资本能够消除公众对银行稳定的预期。

## 资本是重要的监管指标 ##

为了控制风险，监管部门和市场都要求银行的
**风险资产（如贷款）**与银行的
**资本**保持一定的比例。

## 巴塞尔协议与资本监管 ##
20世纪80年代以前，金融监管部门的要求是资本与银行总资产相联系。

20世纪80年代后期，各国金融监管部门逐渐把银行的最低资本额与银行的资产质量联系起来。

1988年，国际清算银行（bank of internatio settlement，BIS）通过了《关于统一国际银行资本和资本标准的协议》（即《巴塞尔协议I》）。

协议规定：商业银行的资本应与资产的风险相联系。**银行资本的主要作用就是吸收和消化银行损失，是银行免于倒闭危机。**

## 《巴塞尔协议I》对银行资本的分类 ##
根据《巴塞尔协议I》，银行资本分类两类：
1. 一级资本（核心资本）：股本，公开储备（资本公积、未分配利润等）。
2. 二级资本（附属资本）：各种准备金，混合资本工具（具有债务和古裙双重性质的资本工具），，长期附属债务。

## 《巴塞尔协议I》对银行资本的要求 ##

1. 核心资本（一级资本）对风险资产的比例不低于4%
2. 总资本（一级资本加二级资本）对风险资产的比例不低于8%。

## 风险资产的计算 ##
风险资产全称是“总加权风险资产”，就是银行的各项资产通过乘以其各自的转换系数后再加总得到的资产总额。

一项资产风险越大，其转换系数越大。

一项资产风险越小，其转换系数越小，最小为0。

## 风险资产计算的例子 ##

## 《巴塞尔协议II》对资本要求的改进 ##

1. 加入
**市场风险资本要求**
与
**操作风险资本要求**

2. 核心一级资本（股本）对风险资产的比例不低于4.5%
3. 一级资本对风险资产的比例不低于6%。
4. 总资本（一级资本加二级资本）对风险资产的比例不低于8%。

## 《巴塞尔协议III》 对资本要求的改进 ##

次贷危机后，很多银行因为没有考虑表外资产的风险而破产，为此巴塞尔委员会加入了非风险杠杆率要求：

> 非风险杠杆率 = 一级资本／（资产 + 表外风险暴露）

该指标要求不低于3%。

