---
title: "第五章  贷款政策与管理"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---


## 贷款的重要性与金融体制特征有关 ##

* 在金融市场发达的国家，大量融资需求可以通过资本市场进行，贷款的重要性较低。

* 在金融市场不发达的国家，资金融通活动高度依赖银行体系，中国是典型。

## 贷款在我国银行体系中的重要性 ##

* 贷款资产占银行总资产的三分之二以上

* 贷款收益占银行总收益的四分之三以上


## 贷款的种类 ##

* 按借款人性质划分：公司贷款、个人贷款

* 按贷款期限划分：短期、中期和长期

* 按有无担保划分：**信用贷款**、担保贷款

* 按照银行贷款的资金来源以及贷款中银行所承担的风险划分：自营贷款和委托贷款

## 贷款的用途：流动资金贷款

* 为了弥补企业流动资产循环中所出现的现金缺口，

* 满足企业在生产经营过程中临时性、季节性的流动资金需求，

* 或者企业在生产经营过程中长期平均占用的流动资金需求，

* 保证生产经营活动的正常进行而发放的贷款。

## 贷款的用途：固定资产投资贷款

* 基本建设贷款：厂房设备等

* 技术改造贷款

* 科技开发贷款

* 商业网点贷款

## 贷款对象的评估原则 ##
6C原则：

1. 品质-character ：信用记录

2. 能力-capacity ：履约能力

3. 现金-cash ：现金流

4. 抵押-collatera ：抵押品的价值

5. 环境-condition ：借款人所在行业的周期

6. 控制-control ：监管政策

## 贷款协议的内容

* 贷款金额、期限、**贷款用途**的规定；利率与计息；

* 提款条件、提款时间及提款手续；

* 还款；担保；保险；声明与承诺；违约事件及处理；

* 扣划；税费；抵销、转让与权利保留；

* 变更与解除；法律适用、争议解决及司法管辖；附件

## 贷款的业务流程 ：申请与授信

1. 贷款营销与借款人申请
    * 贷款营销：寻找符合银行业务发展规划和风险战略的贷款机会 
    * 借款人要提出正式书面贷款申请 

2. 信用评级与授信额度核定


## 贷款的业务流程：贷款调查、审批与发放

* 贷款调查与分析

* 贷款审批

* 借款合同

* 贷款发放

## 贷款的业务流程：贷后管理

* 贷后检查

* 贷款风险预警

* 贷后管理责任制

## 贷款政策：贷款前风险控制政策 ##

1. 贷款的发展战略：确定银行的资产扩张速度

2. 贷款的分级授权审批政策。

3. 贷款的期限和品种结构：银行能接受的最长贷款期限

4. 贷款的审批和管理程序

## 贷款政策：贷中政策 ##

1. 贷款发放规模的控制

2. 关系人贷款政策

3. 信贷风险集中度管理政策

4. 担保政策

5. 定价政策

## 贷款政策：贷后管理政策 ##

1. 贷款档案管理政策

2. 贷款的日常管理和催收政策

3. 贷款质量标准评价政策

4. 不良贷款的处理政策

## 贷后审查

* 贷款发放后，借款人会因主客观因素的变化导致借款质量发生变化。如经济周期波动、个人职业变化等，都会影响借款人的清偿能力。

* 贷款审查可以帮助银行的管理层迅速发现有问题贷款，检查信贷政策的执行情况，提供预警信号，及时发现贷款质量变化，防止贷款质量恶化。

## 贷后审查的原则

* 定期对所有类型的贷款进行审查，大笔贷款审查周期较短，小笔贷款可以随机抽样审查；

* 调查借款人的财务状况与还款能力；

* 审查贷款文件的完整性和贷款政策的一致性；

* 调查银行对抵押和担保的控制程度；

* 特别关注有问题的贷款。

## 贷款的五级分类标准 ##

1. 正常类：借款人能履约

2. 关注类：借款人目前尚有能力还本付息，但存在对偿还不利的因素

3. 次级类：借款人还款能力出现问题，其正常经营收入已经无法保证足额偿还本息

4. 可疑类：借款人无法足额偿还本息，即使执行抵押或担保，也会给银行造成部分损失

5. 损失类：在采取一切措施和法律程序后，本意依然无法收回，或者只能收回极少部分

## 贷款风险分类的目的

* 揭示贷款的实际价值和风险程度，真实、全面、动态地反映贷款的质量；

* 发现贷款发放、管理、监控、催收以及不良贷款管理中存在的问题，加强信贷管理；

* 为计提贷款损失准备金提供依据。


## 不良贷款 ##

* 次级，可疑和损失类三类贷款合称**不良贷款**。

* 不良贷款与全部贷款余额的比重称为**不良贷款率**

* 不良率反应银行贷款质量的恶化程度

## 我国不良贷款率变动图 ##



## 不良贷款的判断指标：经营指标 ##

1. 企业管理风格的改变，高管人事变动。

2. 企业所处行业和主营业务产品的变化。

3. 企业信息提供态度的变化。

## 不良贷款的判断指标：财务指标 ##

1. 杠杆率的变化，若企业杠杆率超越行业平均水平则值得警惕。

2. 盈利能力的变化。

3. 企业流动性的变化，流动性对于非金融企业同样重要。

## 判断还款可能性的考虑因素

* 借款人的还款能力

* 借款人的还款记录

* 借款人的还款意愿

* 贷款的担保

* 贷款偿还的法律责任

* 银行的信贷管理

## 问题贷款的处理程序 

* 与借款人会面，商讨合作的可能性，如果可能的话，银行会继续向借款人注入新的资金。 
* 当追加资金方案不能选择时，银行和企业还可以协商制定一个双方同意的政策。 

* 当银行与企业双方无法实现上述目标时，则只有清算最后一种选择了。 

## 处理不良贷款的主要方法

* 贷款重组：银行对有信心的企业使用

* 人员重组

* 收购兼并

* 债转股

* 贷款转让：折扣卖给其他机构

* 以物抵债

* 起诉破产

* 贷款核销

## 呆帐准备金 ##

* 贷款呆帐准备金是从银行收入中提取的，用于弥补贷款损失的一种预备资金。

* 银行提取呆帐准备金的唯一目的是弥补信贷业务的坏账损失。

* 银行提取呆帐准备金要符合两项原则：一是及时性原则，二是充足性原则。 

## 呆帐准备金计算 ##

在普通呆帐准备金和专项呆帐准备金体系下，准备金的计算步骤如下：

1. 计算所需的专项呆帐准备金。不同类型贷款呆帐计提的参考比例：损失类贷款为100%；可疑类贷款为50%；次级类贷款为20%；关注类贷款为5%。

2. 计算普通呆帐准备金。正常类贷款需计提普通呆帐准备金。方法为：

> 普通呆帐准备金＝（贷款总额—专项呆帐准备金）×规定的比例

3. 呆帐准备金总量＝专项呆帐准备金＋普通呆帐准备金




