---
title: "第一章导论"
author: "Qiufei"
date: "2/6/2017"
output:
  revealjs::revealjs_presentation:
    theme: sky
keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 破产为什么叫bankruptcy ##

* bank 源自意大利语banca，意思是长凳。

* 西欧最早期的银行家每人在市场上有一个长凳（banca），以此作为他们经营的场所，所以他们被称之为banca。

* 如果这些人周转不灵，无力偿付债务时，债务愤怒之下会砸了（rupt）他们吃饭的家伙。

* 所以银行经营失败就被称之为bankrupcy。后来所有经营失败，信用破碎的情况，都被称之为bankrupcy。

## 商业银行是经营信用的机构 ##

## 信用与风险是一对孪生兄弟 ##

## 金融机构的核心功能是管理风险 ##

本课程的目的：

1. 分析目前金融服务供应商面临的各种风险，

2. 以及处理这些风险的方法。

## 商业银行的作用 ##

1. 信用中介。

资本盈余与短缺之间的调剂。对实体经济而言，就是将储蓄转换为投资。

2. 支付中介。

支付宝

3. 信用创造。

不完全存款准备金制度使得银行体系可以创造派生贷款。

4. 金融服务。


## 银行的组织类型 ##

1. 单一制银行

2. 分支行式银行

3. 银行控股公司

4. 金融控股公司

## 单一制银行 ##

* 传统banca的继承者。

* 在美国较为多见，因为美国联邦制下，各州都反对金融权利集中。

## 分支行式银行 ##

目前大部分国家，包括中国，都是实行这种银行体制。

## 银行控股公司 ##
* bank holding company: 是持有至少一家银行的股份而获得特许经营的公司。通常也兼营其他业务。

> 《银行控股公司法》：一家控股公司持有至少一家银行25%以上的股份，或者能指派至少一家银行两名以上的董事，就认为该控股公司对该银行存在控制行为。这种控制行为必须得到美联储（fed）的特许。

* 这是美国金融机构为了规避各州对银行跨州经营的限制而建立的组织结构。

## 金融控股公司 ##

* financial holding company：
控制公司是金融机构，且其他业务也是金融业务的银行控股公司。

## 银行组织结构演进的方向：混业、全功能 ##

银行向混业全功能机构转变，除了给消费者提供便利金融服务的考虑外，还有以下经营上的原因：

1. 便利的从资本市场筹集到资金。因为商业银行有中央银行的支持。

2. 通过集团内关联交易获得谁税收上的好处。

3. 规避分业监管的限制。


## 我国的金融控股公司 ##
* 全牌照集团。

* 获取分业监管，准入限制下的垄断利润。

## 商业银行的经营原则 ##

* **有效控制风险。**

> 一个笑话：银行是一个只要你能证明你不需要钱，才能从哪里借到钱的地方。

