---
title: "第九章  商业银行中间业务"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

## 中间业务出现的背景

* 20世纪70年代以来，金融技术的进步，非银行金融机构的壮大，证券市场迅猛发展导致的资本“脱媒”。

* 国际银行业受到的监管特别是对资本充足率的监管日益严格，迫使国际银行业寻找新的利润来源。

* 于是商业银行通过大力开展中间业务，开发创新产品，开辟新的盈利空间。 

## 中间业务定义 ##

商业银行从事的，按照通行会计准侧：

1. 不列入资产负债表

2. 不影响资产负债总额

3. 但会改变银行当期损益的活动。

## 表外业务种类：巴塞尔定义 ##

巴塞尔委员会对表外业务按照是否构成银行或有资产和或有负债，将表外业务分为两类：

1. 或有债权/债务类表外业务。

2. 金融服务类表外业务。

## 《商业银行中间业务暂行规定》的分类 ##

1. 支付结算类中间业务 

2. 银行卡业务 

3. 代理类中间业务 

4. 担保类中间业务 

5. 承诺类中间业务

6. 交易类中间业务

7. 基金托管业务 

8. 咨询顾问类业务 

9. 其它类中间业务

## 中间业务的类型 ##

按照风险大小和是否含期权期货性质将中间业务分为3大类

1. 无风险／低风险类中间业务

2. 不含期权期货性质风险类的中间业务

3. 含期权期货性质风险类的中间业务

## 无风险／低风险类中间业务 ##

商业银行

* 不运用或较少运用自己的资金

* 以中间人的身份

* 为客户提供代理收付、委托、保管、咨询等金融服务

* 并收取中介手续费

## 咨询类中间业务 ##
商业银行依靠自身在信息、人才、信誉等方面的优势，转让、出售信息，提供企业并购、财务顾问等服务为主要内容的业务，并收取一定的服务费。 

1. 评估型咨询：项目评估、企业信用等级评估

2. 中介型咨询：资信调查、专项调查

3. 综合类咨询：管理咨询、并购咨询、投资银行咨询、财务顾问咨询

## 代理类中间业务 ##
商业银行接受客户委托、代为办理客户指定的经济事务，提供金融服务并收取一定费用，是典型的中间业务。

1. 代理收付业务：代发工资、代收水电煤气、代收税款

2. 代理承销与兑付债券业务：代发国库券、代理证券资金转账

3. 代理保险

4. 代理委托贷款业务：帮助委托人发放贷款

5. 代理财政委托业务

## 基金类中间业务 ##

1. 基金管理：商业银行设立基金管理公司，目前我国只允许商业银行设立货币基金和债券基金。

2. 基金托管业务

3. 基金代销


## 不含期权期货性质风险类的中间业务 ##
此类业务中，商业银行：

* 会承担一定的风险

* 但银行与客户的风险是对称的

* 客户不拥有单独决定是否履行合同的权利

## 交易类中间业务 ##

**代客**

* 债券买卖

* 外汇买卖

* 结售汇

* 金融衍生品

* 黄金买卖

银行在开展此项业务时不仅可以获得差价或手续费收入，还可以吸收到保证金存款。

## 支付结算类中间业务  ##

结算一般分为现金结算和转账结算两种方式，但是我国习惯上将转账结算简称为“结算”。

1. 汇兑结算：汇款

2. 票据结算：银行汇票，商业汇票，银行本票，支票结算

3. 托收结算：跟单托收，光票托收

4. 信用证结算

5. 网上银行

## 银行卡业务 ##

1. 借记卡

2. 信用卡：贷记卡和准贷记卡

##  含期权期货性质风险类中间业务  ##

商业银行向客户提供此类中间业务时：

* 会形成银行潜在的债权债务关系，

* 银行应承诺购买方的要求，保证将来按照事先约定的条件履行承诺。

* 这对于银行来说是一种或有债权/债务

## 担保类业务 ##
担保类中间业务指商业银行为客户债务清偿能力提供担保，承担客户违约风险的业务。

* 银行承兑汇票

* 银行保函

* 备用信用证

## 案例--信用证与银行承兑汇票 ##

交易各方：

- 千里进出口公司

- 德国小众汽车公司

- 中国千里银行：千里进出口公司的开户行

- 德国小众银行：小众汽车公司的开户行

- 万里云货币基金

## 交易内容 ##

- 千里进出口公司打算从小众汽车公司买15辆最新款跑车

- 千里公司向小众公司下了单

-  但是小众公司担心15辆车送到的时候，千里公司可能没有足够的资金付款

## 信用证救场 ## 

- 于是千里公司向小众公司提出用信用证来进行交易

- 千里公司为15辆跑车支付3亿的购车款

- 千里公司收到小众公司15辆跑车的60天后付款

## 开证 ## 

- 千里公司跟它的开户行千里银行联系，开立一张信用证

- 信用证的内容是，千里银行保证，在千里汽车公司受到跑车60天后，向小众汽车公司支付3亿购车款

- 千里银行将信用证寄给小众银行


## 发货与收款 ## 

- 小众银行接受到信用证后，通知小众汽车公司发货

- 小众汽车公司发货后，将发货凭证寄给小众银行

- 小众银行将3亿元购车款的现值交付给小众汽车公司至此，小众汽车公司已经推出此交易链条

## 银行承兑汇票的生成 ## 

- 小众银行将信用证和发货凭证寄给千里银行

- 千里银行在受到凭证后，在信用证上加盖“接受”章，于是千里银行生成了一份银行承兑汇票（bankers acceptance）。这意味着千里银行将在汇票到期后向持有人支付3亿元款项。

- 千里银行与千里公司签订一个融资协议后，千里银行把提货单交给千里公司

- 此时，银行承兑汇票的持有人是小众银行

## 小众银行的两种选择 ## 

- 将银行承兑汇票持有到期

- 将银行承兑汇票在千里银行贴现

## 千里银行的两种选择 ## 

- 持有到期

- 卖给投资者，比如货币基金万里云

## 汽车到货六十天后 ## 

- 万里云公司将银行承兑汇票交付给千里银行，从千里银行那里获得3亿款项

- 千里银行从千里汽车公司那里获得3亿元款项

- 交易结束

## 承诺类中间业务 ## 

承诺类中间业务是指商业银行在未来某一日期按照事前约定的条件向客户提供约定信用的业务，主要指借款承诺，包括可撤销承诺和不可撤销承诺两种。

* 贷款承诺

* 票据发行便利

* 回购协议


## 金融衍生产品 ##

金融衍生产品，通常是指从基础资产（Underlying Assets）派生出来的金融工具，它是一种金融合约，其价值取决于一种或多种基础资产或指数。


* 远期

* 期货

* 掉期（互换）

* 期权

* 以及具有以上多种特征的结构化金融工具

## 租赁类中间业务 ##

租赁是指以收取租金为条件，让渡物件使用权的经济行为。

1. 融资租赁：长期租赁

2. 经营性租赁：短期租赁

## 商业银行中间业务产品的定价


- 定价影响因素

- 实用实用模型


## 定价模型应用--支票


- 固定成本与变动成本

- 年度成本

- 盈亏平衡分析

