---
title: "国际银行"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 背景

- 跨国公司的规模、经营方式、产业结构均发生了前所未有的变革，国际金融市场迅猛发展，为各国商业银行拓展国际业务提供了广阔的空间和巨大的商机。

- 越来越多的商业银行抓住机遇，扩大国际业务的规模与范围，到国外设立分支机构，提高金融服务的水平和质量，加入到跨国银行的行列中。 

## 商业银行的国际扩张 
-    20世纪90年代以后，很多国家相继放松了银行业
的管制。
-   国际业务可以使商业银行在多个经济体中实现业
务的多样化，这也是诸多商业银行在世界范围内设
立分行的原因所在。
-   各家商业银行在从事海外业务时可以更多地为跨
国公司服务，从而提高商业银行的国际化专业水平

## 商业银行的海外业务机构形式

- 代表处（Representative Office）：只是做公关
- 代理处（Agency Office）：不能吸收当地存款
- 海外分支行（境外联行）(Overseas Sister Bank/Branch, Sub-branch)
- 附属银行（子银行）（Subsidiary Banks）：收购东道国银行的股份
- 代理银行(Correspondent Banks)：业务互相委托
- 联营银行（Affiliated Bank）：50%
- 银团银行（Consortium Bank）：50%

## 商业银行的全球竞争

随着全球金融市场一体化的发展，任何国家的银行所面对的主要竞争对手不仅有本国银行,还有外资银行，全球的银行竞争将更加激烈。

- 商业银行在海外设立分支机构的数量增加
- 投资银行服务的竞争，全球竞争激烈的典型业务就是承销、经纪等投资银行业务 
- 欧元的诞生也对全球银行业竞争产生了巨大的影响 

## 全球银行业运行规则

世界范围内也存在统一化的全球银行业运行规则。其中，最有意义的三个规则是：《国际银行业法案》、《单一欧洲法案》和《巴塞尔协议》。

- 1978年的《国际银行业法案》的主旨是对全美国的国内外银行施加相同的监管 
- 1987年的《单一欧洲法案》消除了欧洲各国银行业务接受存款等方面的资本管制，提高了欧洲金融市场的效率，促进了欧洲银行的整合趋势。
- 1988年的《巴塞尔协议》规定了各国银行资本充足率的标准 

## 外资银行在中国

- 早在19世纪50年代，汇丰、渣打等外资银行就进
入了中国市场。但在其后的150年里，外资银行在
中国发展非常缓慢。直到2001年中国加入世界贸易
组织（WTO）以后，外资银行才开始在中国大规模
地进行扩张。

- 外资银行在中国的业务机构主要是分行和代表处

## 外资行的业务特点

- 从地域上看，这些业务机构主要集中在大中城市和沿海发达地区。

- 外资银行进入中国市场之初只能开展有限的外汇业务，但随着中国逐渐开放金融市场，目前外资银行已经能开展全方位的外汇业务和在部分城市开展人民币业务。 

- 随着业务范围的扩大，外资银行的市场份额也迅速提高。 

## 跨国银行的风险管理 
   跨国银行要面对不同的政治、法律环境，对外国
客户往往难以彻底了解，而且还要面对各种不同的
货币。

- 信用风险
- 市场风险
- 结算风险
- 政治风险
- 法律风险

## 跨国银行风险管理的基本方法

- 风险价值法(VAR)
VAR方法把银行的全部资产组合风险概括为一个简
单的数字，并以美元计量单位来表示风险管理的核
心——潜在亏损

- 风险调整的资本收益法(Raroc)
风险调整的资本收益是收益与潜在亏损或VAR值
的比率。以资金投资风险基础上的盈利贴现值作为
依据来对其资金使用进行决策

## 国际结算业务

国际结算及其原则国与国之间，由于政治、经济、文化及事务性的
交往和联系均会产生债权债务关系或资金授受行
为，以货币收付来清偿债权债务及实现资金转移的
行为即为国际结算（International Settlement）

- 按在银行业务中差异，分为国际贸易结算与非贸易国际结算。其中核心部分是国际贸易结算。
- 按资金运送方式不同，分为现金结算和非现金结算。

## 国际结算的原则是：

- 同一银行的支票内部转账；
- 不同银行的支票交换转账；
- 按时合理的付汇；
- 安全迅速的收汇。

## 国际结算工具

- 使用票据这种支付工具，通过相互抵账的办法来结算国内外债权债务关系的。

- 票据是具有一定格式，由出票人签发的无条件约定自己或要求他人支付一定金额，并经过背书可予以转让的书面支付凭证
- 票据一般包括汇票、本票、和支票。在国际结算中，以汇票为主，本票和支票居于次要地位。

## 国际结算有三种基本形式
- 汇款、
- 托收、
- 信用证。

从资金与票据的流动方向是否一致来看，汇款属于顺汇（to Remit），又称汇付法。托收和信用证则属于逆汇(to Draw a Draft),又称出票法。


## 顺汇方式--外汇支付型 

顺汇是由汇款人主动委托银行以某种信用工具将款
项支付给收款人的一种支付方法。由于这种支付方式
的资金流向与信用工具的传送方向相同，因而称为顺
汇。

- 顺汇的基本当事人：
     1. 汇款人，通常是债务人或付款人；
     2. 收款人，是债权人或受益人；
     3. 汇出行，是受汇款人委托向收款人汇款的银行；
     4. 解付行，是受汇出行委托，接受汇出行的汇款并
向收款人解付款项的银行，也称作汇入行。

- 汇出行与解付行的关系是委托代理关系。

## 逆汇方式--外汇收取型

- 逆汇是由收款人出票，通过银行向付款人收取款项的一种方式。由于这种方式的资金流向与信用工具的传递方向相反，因此称为逆汇。

- 逆汇是国际贸易中支付使用广泛的一种方式。按照逆汇方式下信用形式的不同，分为托收和信用证。

## 托收方式
         
- 托收是由债权人（出口商）主动向国外的债务人（进口商）开立汇票，
- 并委托本地外汇银行通过其在国外分行或代理行，
- 向债务人收取款项的一种结算方式。
        
## 信用证（Letter of Credit,简称L/C）

- 信用证是指开证行根据申请人（进口商）的申请和要求，对受益人（出口商）开出的授权出口商签发以开证行或进口商为付款人的汇票，并对提交符合条款规定的汇票和单据保证付款的一种银行保证文件。

- 信用证方式是最主要、最广泛的国际结算方式

## 外汇买卖

- 是银行最基本的国际业务，是将
一种货币按照既定的汇率兑换成另一种货币
的活动。
- 银行外汇买卖业务的对象主要是银行同业以及
有外币兑换需求的贸易企业、跨国公司、政府及个
人。

- 银行同业之间的外汇买卖规模大、买卖差价
小，属于批发性业务；银行与一般客户之间的外汇
买卖规模小、买卖差价大，属于零售业务。


## 外汇从业务性质分类

银行的外汇业务可以分为

- 即期外汇买卖业务、
- 远期外汇买卖业务、
- 外汇衍生工具买卖业务。

其中，规模最大的是即期外汇买卖业务

## 即期外汇买卖业务

- 是指按照银行的即期外汇牌
价，在两个交易日内完成资金交割的货币兑换行
为。
- 外汇牌价是外汇买卖使用的交易价格，由买价
和卖价组成。

- 买价与卖价的差价实际上是银行提供
兑换业务的佣金。

## 远期外汇业务

- 是指交易双方同意在将来某一个确定的日期，按照事先规定的远期汇价买卖一定数量的某种货币的交易行为

- 远期外汇业务最重要的功能是套期保值，此外也可以借此进行外汇投机 

## 外汇衍生工具买卖业务

- 外汇掉期业务（Foreign Exchange Swap）指在一笔外汇交易中同时进行即期和远期的外汇买卖行为。当外汇交易的一方从对方买进或者卖出一定数量的即期外汇（远期外汇）时，交易的另一方也同时向对方或者第三方卖出或者买入相同金额的远期外汇（即期外汇）。
- 外汇期货业务（Foreign Exchange Future）是指在集中性的交易市场以公开竞价的方式进行的外汇期货合约的交易。
- 外汇期权业务（Foreign Exchange Options）是指以某种外币或外汇期货合约作为标的物的期权。

## 国际信贷

- 是指一国的商业银行或其他金融机构，在国际金融市场上，

- 向另一个国家的银行、其他金融机构、政府、公司企业以及国际机构提供贷款。 


## 国际银团贷款

- 是指由一家或几家银行牵头，多家跨国银行参加，共同向一国政府、某一企业或某一项目提供贷款的一种方式。
- 国际银团贷款又称国际辛迪加贷款。
- 它产生于20世纪60年代后期。 

## 国际银团贷款的种类 

- 按贷款期限可分为定期贷款和循环贷款 
- 按贷款人和借款人的关系分为直接银团贷款和间接银团贷款
- 此外还有备用贷款、备用信用证保证贷款等。

## 国际贸易融资

- 贸易融资，是指商业银行对进出口贸易的资金融通。 

- 根据期限的长短，贸易融资可以分为短期贸易融资和中长期出口信贷。

## 中长期出口信贷

- 中长期贸易融资不论是对出口商提供的，还是对进口商提供的，提供的目的都是为了促进本国的出口，加强本国商品的国际竞争力 
    1. 它是一种与本国出口密切联系的贷款。
    2. 是一种具有官方资助性质的政策性贷款。
    3. 贷款利率低于市场利率，利差由出口国政府补贴。
    4. 出口信贷与信贷保险相结合。


- 出口信贷有卖方信贷、福费廷、买方信贷等形式。 

## 项目融资

- 是一种贷款人没有完全的追索权，依赖项目的资产和现金流量，资金回报和费用较高的新型融资方式

- 根本特征是有限追索和风险分担适应跨国公司业务发展的需要

## 国际贷款协议

近年来，国际贷款协议有越来越复杂，内容越来越多的趋势。其原因在于：

1. 国际贷款协议的灵活性增强。
2. 当今国际金融局势日趋动荡。
3. 国际银团贷款、项目融资等新的贷款方式发展迅速


## 国际银行业的监管

- 在国际范围内对银行进行监管（supervision）
与规范（regulation）,这在一个正常运作的世界经
济体制中是十分重要的因素。没有适当的监管，银
行也就无法正常执行其信贷机构以及国家支付系统
的职能，还会跨国界对其他国家的银行体系产生危
害。

- 这些影响包括：通过企业集团或控股公司的结构
来自我放贷；受到其他金融市场的传染；不完善的
信贷政策指导原则；经营不善。








         







