---
title: "第四章  商业银行现金管理"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---


## 现金管理对银行的重要性 ##

* 商业银行的经营对象是货币

* 因此银行必须保持合理的流动性应付存款提取与结算需要

* 现金资产能够直接满足流动性需求

## 现金资产的构成 ##

狭义的现金资产指的是银行的库存现金，广义的现金资产则包括以下四个部分。

1. 库存现金 

2. 托收中的现金 

3. 在中央银行的存款

4. 存放同业的存款

## 库存现金

* 商业银行保存在金库中的现钞和硬币 

* 作用:  银行用来应付客户提现和银行本身的日常零星开支

* 经营原则:  保持适度的规模

## 存款准备金与现金管理 ##

* 商业银行在央行的存款称之为准备金存款

* 准备金存款分为两个部分：
  1. 法定准备金存款
  2. 超额准备金存款

## 法定存款准备金 ##

* 最初是为了保证银行有足够的资金，以应付存款人的提取。

* 在存款保险制度实施后，法定存款准备金成为央行的货币政策工具：
   
   1. 提高法定存款准备金，商业银行能动用现金较少，信贷扩张能力减弱，收紧的政策。
   2. 降低法定存款准备金，商业银行能动用现金提高，信贷扩张能力增强，宽松的政策。


## 超额存款准备金 ##

* 商业银行的法定准备金与超额准备金都存放在中央银行的基本账户里

* 但法定存款准备金一般不得动用

* 超额准备金则是商业银行可以自由动用的部分，可用来投资、贷款、清偿债务和提取业务周转金。

## 法定存款准备金的计算：滞后准备金计算法

* 滞后准备金计算法是根据前期存款负债的余额确定本期准备金需要量的方法。

* 这种方法主要适用于银行对非交易性账户存款计算存款准备金。因为非交易性存款账户如银行的定期存款等，其余额的变动幅度相对较小。


## 法定存款准备金的计算：同步准备金计算法

* 同步准备金计算法的基本原理是：以本期的存款余额为基础，计算本期的准备金需要量。

* 这种方法主要适用于商业银行的交易性账户存款计算准备金。交易性账户余额的变化幅度较大，商业银行应该根据本期存款余额的实际状况，计算所需上缴的准备金数额。

## 现金资产管理的目的及原则  ##

* 现金资产管理的目的就是要在确保银行**流动性**需要的前提下，尽可能地降低现金资产占总资产的比重，使现金资产达到最适度的规模。

* 基本原则：
     1. 适度存量控制原则
     2. 适时流量调节原则
     3. 安全性原则

## 现金资产与流动性 ##

* 银行的流动性供给包括：一是在资产负债表中存储流动性，二是从金融市场上“购买”流动性。


* 银行的现金资产作为资金运用的一部分，直接形成了对流动性的供给。

## 银行流动性需求的预测 ##

* 流动性需求供给不匹配是商业银行日常经营的常态，

* 准确预测流动性需求是银行进行现金资产管理的首要任务

## 流动性需求增加的因素  ##

* 客户提取存款
* 合格贷款客户的贷款要求
* 偿还非存款借款
* 提供和销售服务中产生的营业费用和税收
* 向股东派发现金股利 

## 流动性需求预测：因素法

* 存贷业务是影响银行流动性的主要因素

> 资金头寸需要量=预计贷款增量+应缴存款准备金增量-预计存款增量

## 影响贷款变化的因素

* 预期经济增长率

* 企业预期利润率

* 预期M2增速

* 预期利率

* 预期通胀率

## 影响存款变化的因素

* 个人预期收入增长率

* 社会零售品预期增长率

* M2预期增长率

* 预期存款利率

* 预期通胀率

## 流动性需求预测：资金结构法

* 资金结构法是通过分析存贷款资金结构及其变化趋势来预测未来的流动性需求。

* 银行总流动性需求=存款和非存款负债的流动性需求+贷款的流动性需求。

## 结构分析

* 将存款分为流动性、脆弱性和稳定性三类

* 对不同的存款类型保持不同比率的流动性准备

* 对新增贷款需求保留100%的准备资金。

> 银行理论上可以根据资金多寡决定贷款业务规模，但是在实际经营中，银行是按“客户关系准则”出发，满足客户合理的新增贷款需求。


## 流动性需求预测：流动性指标法

* 流动性指标体系能够反映一家银行整体的流动性状况。

* 银行可以通过对比分析自身的流动性指标与同行业的平均水平来估算其流动性需求。

## 银行流动性问题的成因

银行的流动性问题成因：

1. 资产负债的错配

2. 银行风险的集聚

## 资产负债的错配

* 期限的错配：到期资产的数量（现金流入）与到期负债的数量（现金流出）不对称 

* 币种的错配：到期资产的币种与到期负债的币种不对称 

* 分布的错配：资产的运用对象与负债的运用对象不对称 


## 银行风险的集聚 

* 信用风险、市场风险、操作风险、法律风险、声誉风险及战略风险等长期积聚 

* 流动性归根到底是信息的游戏。

## 银行流动性危机的路线图

1. 银行盲目高速增长，承担大量风险

2. 宏观环境或是内部管理恶化，出现巨额损失

3. 银行的损失被市场所知，被媒体渲染，引起金融市场的恐慌

4. 银行出现流动性困难，不得不提高利率挽留现有客户，同时抛售资产环节流动性不足

5. 银行提高利率和抛售资产的行为，让市场确认它的确遇到了麻烦，于是客户流失，债权人拒绝战旗，资产价格暴跌纷至沓来。

## 银行流动性管理理论的发展

* 资产管理理论
      1. 商业贷款理论（Commercial Loan Theory） 
      2. 资产转换理论（Shiftability Theory） 
      3. 预期收入理论（Anticipated Income Theory） 

* 负债管理理论：以负债的方法来保证银行流动性 

* 资产负债综合管理理论：强调对银行的资产和负债进行全面地管理 

## 商业银行流动性需求管理的原则 ##

商业银行在流动性管理中一般会选择以下某种原则：

1. 进取型原则

2. 保守型原则

3. 成本最低原则

## 进取型原则 ##

* 当出现流动性缺口时，银行不是依靠收缩资产规模、出售资产

* 而是通过**负债**借入新的资金来满足流动性需求。

    > 一般为实力雄厚的大银行所采用

## 保守型原则 ##

* 当出现流动缺口时，通过自身资产转换、出售的方式来满足需求

* 所谓**转换**，就是在资金需求的淡季，加大准备金的比例，为资金需求高峰期做准备。

	> 一般为融资成本较高的小银行所采用

## 成本最低原则 ##

* 综合考虑进取和保守两种方式，看那种方式成本低。

* 教材没说适用那种银行，但是推测应该是适用于中型银行。

> 为什么做这种推测？



## 流动性需求管理效果的衡量 ##

1. 公众对银行的信心。
2. 银行股票价格是否稳定。
3. 发行负债产品时是否存在风险溢价。
4. 出售银行资产有无损失。
5. 能否满足客户的合理贷款需求。
6. 是否频繁从中央银行借款。



