---
title: "中国银行业经营现状"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 本章内容

- 电子银行业务的兴起
- 主要的电子银行业务
- 电子银行的风险
- 电子银行的未来发展趋势


## 电子银行兴起： 商业银行电子化

- 银行结算自动化：20世纪50-70年代

- 自助银行服务：70-80

- 网上银行服务:90至今

## 电子银行兴起：电子货币

- 储值产品和预算支付机制

- 通常以银行卡为基础

- 从起初单纯概念上的信用卡发展到网络支付工具

## 电子商务

- 广义的电子商务可定义为：电子工具在商务活动中的应用 
- 狭义的电子商务可定义为：在技术、经济高度发达的现代社会里，掌握信息技术和商务规则的人，系统化运用电子工具，高效率、低成本地从事以商品交换为中心的各种活动的总称

- 商业银行适应电子商务的发展

## 电子银行

- 电子商务是电子银行产生的商业基础,电子商务的发展催生了电子银行 
- 电子银行，是指通过网络和电子终端为客户提供自助金融服务的虚拟银行。电子银行通过电话银行、网上银行、手机银行等为客户提供查询、转账、理财和支付结算等服务。
- 网上银行逐渐发展成为我国商业银行为高端客户提供服务的主要方式。

## 电子银行的演变过程

电子银行是银行电子化的结果，从计算机发明开始，50年的银行电子化历程可以分为四个阶段 
- 第一阶段：20世纪60年代的后台电子化
- 第二阶段：20世纪70年代的前台电子化
- 第三阶段：80年代的网络化
- 第四阶段： 90年代的网上银行

## 电子银行的特点

- 以计算机技术为基础，以网络为媒介

- 客户自助服务
2016年四大行的裁员
- 全天候服务
- 低边际成本

- 业务综合性强

## 电子银行对商业银行经营的影响 

电子银行作为一种新的金融服务提供方式，既对传统银行业提出了严峻的挑战，也给银行业发展带来了新的机遇。

对于商业银行的经营而言，其积极影响如下 
- 提高了工作效率 
- 改善了服务质量 
- 有利于提供更多的金融服务项目和支付手段 
- 加速资金周转 
- 提高了经营管理水平 

## 电子银行业务发展模式 

目前电子银行有两种业务发展模式：

- 一种是传统银行电子化模式，现有的银行运用信息技术和设施提供电子金融服务；
传统银行可通过收购已有的电子银行业务或是开立自己的电子银行业务来发展
- 一种是纯电子银行（即虚拟银行）模式，没有柜台服务，仅仅采用电话、互联网为客户提供金融服务。节约经营成本，无法解决与客户的沟通交流问题，有较高的信息不对称风险。（阿里银行）

## 自助银行
客户在银行计算机网络系统和各种终端设备上，自己动手办理以前由银行职员才能办理的银行业务，自助设备包括：

- POS（point of sales），销售终端

- ATM（automatic teller machin），自动柜员机

- 多媒体自助终端

## 电话银行

- 指银行运用先进的计算机、通讯、语音处理技术和电话信号数字化等技术，
- 在原有业务处理系统上，借助公共电话网络，使客户能通过电话同银行进行金融交易

    
## 手机银行

- 手机银行是将银行业务中有关客户端使用平台的某些业务移到了手机上 
- 将无线通信技术的3A（任何时间、任何地点、任何方式）优势应用到金融业务中，为客户提供在线的、实时的服务

## 网络银行

- 网络银行又称网上银行、虚拟银行，是指利用互联网/WWW技术，通过建立互联网站点和WEB主页，向客户提供各种金融服务的银行机构或虚拟网站 
- 特征可概括为“5W”，即实现为任何人(whoever)在任何时间(whenever)和任何地点(wherever)与任何账户(whomever)用任何方式(whatever)的安全支付和结算 
- 网络银行提供的金融业务大致分为三大类：信息、查询和交易。 


## 电子银行风险种类 
- 安全技术风险
- 战略风险 
- 法律风险：网络的未知领域
- 操作风险 
- 声誉风险

## 电子银行风险管理原则

- 采用严格措施确保电子银行系统技术安全
          主要通过增强网络层和应用层的安全技术来保证系统的安全性能 
- 加强电子银行立法建设 
          2005年4月《电子签名法》正式施行 
- 提高电子银行的监管能力 
          巴塞尔委员会《电子银行风险管理原则》，对网上银行的监管制度进行研究，制定了网络银行风险管理的14条指导性原则 
          
## 电子银行风险管理内容

- 风险预测与识别

- 运用安全技术

- 电子银行业务的内部控制

- 控制电子银行业务外包的风险

- 电子银行业务的信息披露

## 电子银行的未来发展趋势

1. 电子银行向多元化、个性化发展

2. 决策电子化和管理智能化

3. 内部控制将实现程序化硬约束

4. 促进不同类型的金融市场整合












