---
title: "第十章  商业银行风险管理"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---


## 商业银行风险管理概述 ##

1. 银行风险的种类

2. 银行风险管理的流程

3. 银行风险的控制方法

4. 商业银行全面风险管理

## 商业银行面临的风险 ##

1. 信用风险、市场风险、操作风险、流动性风险

2. 战略风险、**声誉风险**、法律风险、合规风险

3. 国家风险

## 风险控制的流程 ##

1. 风险识别 

2. 风险计量：最为困难的环节

3. 风险监测

4. 风险控制

## 风险计量也是最为重要的环节 ##
风控不是消除风险，而是将风险控制在能接受的水平上，这要求：

1. 知道银行能够接受的风险水平

2. 知道银行目前已经承担的风险水平

3. 知道每项风控措施对银行实际承担风险水平的具体影响。要**知道**这些事情，都需要风险的准确计量。


## 市场风险的计量 ##
市场风险有着系统性（无法分散只能套保）、易于计量的特点，其计量方法主要有：

1. 敏感度法

2. 在险价值法(value at risk)

## 敏感度法：缺口分析 ##

1. 确定利率敏感性资产和负债的规模。
    * 利率敏感性资产：给定时间段内重新定价，从而利率变动会影响利息收入的资产。
    * 利率敏感性负债：给定时间段内重新定价，从而利率变动会影响利息支出的资产。
   
2. 利率敏感性资产减去利率敏感性负债，得到一个差额，称之为缺口

3. 通过对未来利率的预测，主动调整缺口

## 缺口分析的优缺点 ##
缺口分析计算简便，清晰易懂，然而有以下几个缺点：

1. 忽略了同一时间段内不同头寸的到期时间的差异

2. 只考虑利率重新定价的风险，未考虑基准利率变动的风险

3. 未考虑非利息收入的变动

4. 只是一种短期分析工具

## 敏感度分析：久期分析 ##

久期（duration）就是加权到期时间。

一般计算公式如下：


$$ D = \frac{PV_{t_0}t_0+PV_{t_1}t_1+PV_{t_2}t_2+...+PV_{t_n}t_n}{PV}$$
 

其中
 
$$ PV = PV_{t_0}+PV_{t_1}+PV_{t_2}+...+PV_{t_n} $$

* 这个是久期计算的一般公式，一般在于它没有说明用何种利率来折现。

## macaulay久期

* 如果用债券的收益率来折现，那么计算得到的就是macaulay久期。

* 金融工具一年内支付m次，在每期支付的金额为$c_i$，还需要支付n次，$\lambda$为到期收益率,那么这项金融工具的macaulay久期计算公式为：

$$ D = \sum_{i}^{n}\frac{i}{m}\frac{c_i}{[1+(\frac{\lambda}{m})]^i}\frac{1}{PV}   $$
$$ PV = \sum_{i}^{n}\frac{c_i}{[1+(\frac{\lambda}{m})]^i} $$



## 久期缺口 ##

总资产（负债）的加权平均久期：

* 首先计算每笔资产（负债）的久期

* 然后根据每笔资产（负债）在总资产（负债）中的比例

* 计算出银行总资产（负债）的加权平均久期

> 久期缺口 = 资产加权平均久期 - 负债加权平均久期 

缺口越大，银行所承受的总体利率风险就越大

## 久期分析的优缺点 ##
久期分析能够估算利率变动对所有头寸的未来现金流现值的潜在影响，从而能够对利率变动的长期影响进行评估。

其不足在于：

* 同样只能反应重新定价风险，但是不反应基准利率变动风险

* 对利率变动幅度较大（大于1%）的情况，其分析结果不准确

## 在险价值法 ##

* 在险价值（value at risk，VAR）：在正常的市场条件和给定的置信水平下，在给定的持有期内，某一项投资预期可能发生的最大损失。

* 例子：假设某项投资组合在1天的持有期内，在99%的置信水平下，所计算得到的在险价值为2万元。这表明在1天之内，该投资的损失有99%的把握不会超过2万元。

## VAR的计算方法 ##

1. 方差-协方差法：嘉定收益变化服从正态分布，然后通过历史数据估计研究对象收益分布的参数值。

2. 历史模拟法：假定历史可以重复，根据研究对象的历史样本来模拟其未来损益分布。

3. 随机模拟法：通过模拟研究对象的随机变化来计算不同场景下的收益率。

## 在险价值法的优缺点 ##

能够将不同也业务不同类别的风险比较和汇总，清楚的反映一家银行市场风险的总体水平。
其不足在于：

1. 因为高度概括，所以对具体风险管理的作用很有限

2. 没有涵盖小概率事件的影响。所谓的压力测试（stress test），就是专门测试小概率事件影响的。

3. 大部分模型只能计算交易业务中的市场风险，不能计算非交易业务的市场风险。


## 信用风险的特点 ##

1. 非系统性：每个借款人的异质性太高。因此分散是信用风险管理的重要方法

2. 非正态分布

3. 信息不对称性严重

4. 数据缺乏：缺乏二级市场、价格不盯市、难以直接观察、违约数据点少

## 信用风险计量的代表性方法 ##

* 现代信用风险计量模型中，最具代表性的是信用计量术（credit metrics）模型。

* 其本质是一个VAR模型

## 信用计量术模型的计算方法 ##

1. 确定适用于借款人的信用级别转移矩阵：一般信用评级公司提供

2. 估算贷款处于不同状态时的价值

3. 估计贷款的在险价值

## 操作风险的特点 ##

1. 损失特殊性：沉默的杀手

2. 形式多样性

3. 管理差异性

4. 难以计量：数据少，要考虑间接成本


## 操作风险的种类

* 内部欺诈（Internal fraud）
* 外部欺诈（External fraud）
* 就业政策和工作场所安全性（Employment Practices and Workplace Safety）
* 客户、产品及业务操作（Clients, Products & Business Practices）
* 实体资产损坏（Damage to Physical Assets）
* 业务中断和系统失败（Business Disruption and System Failures）
* 执行、交割及流程管理（Execution, Delivery & Process Management）


## 操作风险的计量方法 ##

1. 基本指标法：操作风险资本等于前三年中各年正的总收入乘以一个固定比例的平均值
2. 标准法：将银行产品分为八个产品线，每个产品线的总收入乘以不同非比例
3. 高级计量法：通过银行内部的风险计量系统来计算

## 银行风险控制的方法 ##

* 风险分散：多样化
* 风险对冲：自我对冲、市场对冲 
* 风险转移：保险转移、非保险转移 
* 风险规避：业务进入控制
* 风险抑制：事中流程监测
* 风险补偿：风险定价、担保品变现、资产损失准备、利润、资本

## 风险分散

> 不要将所有的鸡蛋放到同一个篮子里。

* 马柯维茨（Markowitz）的**资产组合理论**为风险分散奠定了坚实的理论基础。

* 风险分散是商业银行控制风险最基本、最常用的方法。商业银行能够正常运行，也首先得益于分散。

## 资产组合理论的基本思想

* 并非所有资产的风险都完全相关

* 所以将众多资产组合在一起的话，一部分资产收益的变化可以被其他资产收益的变化减弱或者抵消。

* 分散投资能在保持目标收益旅不变的情况下，降低整个资产组合的风险。

## 风散法控制风险的不足

* 只能消除非系统风险，不能减少系统风险：不能消除篮子坏掉的风险。

* 分散的效果取决于资产组合中各项资产的相关性，相关性越低效果越好

* 分散是有成本的的：分散就是规模不经济

## 风险对冲

通过持有与管理的资产收益波动负相关的资产，以其收益来冲销风险带来的损失

* 自我对冲：商业银行资产负债表内资产的与业务的调整。

* 市场对冲：通过衍生品市场套期保值。

## 风险转移

* 保险转移：购买商业保险，自己购买或者要求信贷客户购买。

* 非保险转移：比如要求贷款要有担保人

## 风险规避

* 不进入某一业务活着市场

* 避免哪些超过自己管理能力活着不具备管理优势的风险

## 风险抑制

* 事中和事后的监测，做到风险预警

* 采取补救措施

## 风险补偿

商业银行不可能避免风险损失，为了在风险损失后还能保持正常运营，商业银行要求风险补偿措施：

* 风险定价：事前收取风险补偿金

* 担保品变现

* 资产损失准备

* 利润

* 资本
