---
title: "第十一章  商业银行业绩评估"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

## 业绩评估的不同标准

* 利润最大化目标的局限：
    1. 利润是一个会计概念
    2. 利润是一个事后评价指标
    3. 利润总是与风险相对应的

* 股东价值最大化（或股东财富最大化）

* 利益相关者的利益

* 约束条件下的股东价值最大化


## 商业银行的经营原则
《中华人民共和国商业银行法》：“商业银行以安全性、流动性、效益性为经营原则。”

1. 安全性

2. 流动性

3. 效益性

## 商业银行的财务评价 ##

* 银行的资产负债表

* 银行的损益表

* 银行的现金流量表

* 银行财务分析的几种主要方法

## 银行的资产负债表 ##

* 资产负债表反映银行在特定日期全部资产、负债和所有者权益的报表，又称财务状况报告表

* 时点报表。反映银行各项资产、负债者权益增减变动的情况以及各项目之间的联系

* 考核各项资金计划的执行结果。为预测未来财务状况和发展前景提供重要的数据和信息

## 资产负债表的结构 ##

* 基本结构是以“资产=负债+所有者权益”这一平衡原理而设计的 

* 资产按其流动性程度的高低顺序排列

* 负债按其偿还期的从短到长排列

* 所有者权益则按其永久性递减的顺序排列

## 银行的损益表  ##

* 损益表反映银行在一定会计期间经营成果的会计报表。

* 通过对损益表进行分析，可以了解银行的经济效益和盈亏情况，找出盈亏增减变化的原因，为经营决策提供依据

* 主要包括收入、支出和收益三大部分

## 损益表的结构 ##

损益表格式主要分为四部分：

* 第一部分反映主要经营业务的构成情况；

* 第二部分反映营业利润的构成情况；

* 第三部分是利润总额；

* 第四部分是净利润

## 银行的现金流量表 ##

* 现金流量表反映银行在一定会计期间内的经营活动、投资活动和筹资活动产生的现金流入和流出情况

* 动态报表。现金流量表解释的是现金变化的结果和财务状况变化的原因

对商业银行而言，现金流量中的现金是指：现金资产和可以视为现金的流动资产

## 现金流量表的结构 ##

主要包括三个部分：

1. 经营活动产生的现金流量

2. 投资活动产生的现金流量

3. 融资活动产生的现金流量

## 银行财务分析的几种主要方法 ##

* 比率分析法

* 趋势分析法

* 结构分析法

* 同业比较分析

* 综合比较分析法

## 比例分析法##

* 资金实力分析指标：存款资产比率

* 风险分析指标：流动性风险比率、利率风险比率、信用风险比率、资本风险比率

* 清偿力分析指标：备付金比率 、短期可销售证券与总资产的比率、流动比率、预计中的资金流入—流出比率

* 经营效率分析指标：资产使用率、财务杠杆比率

* 经营成果分析指标：资产收益率、资本收益率、银行利润率、银行利差率 

## 结构分析法 ##

* 将某一项目，划分为若干组成部分，分析部分与整体的比例关系

* 计算公式为：结构百分比＝部分 / 总体×100%

* 通常，银行损益表的总体是收入，资产负债表的总体为总资产

## 同业分析法 ##

* 需要行业经营业绩的平均指标

* 通过本银行的数据与同业值相比得知自己的竞争地位

## 银行盈利能力分析 ##

* 衡量银行盈利性的指标主要是资本收益率

* 资本收益率没有考虑杠杆因素的作用

* 银行资本杠杆作用的放大蕴含着巨大的风险，结合资本杠杆比率可对银行业绩作出更准确的评价

## 商业银行的监管评级：骆驼评级体系

CAMELS

1. 资本充足性(Capital Adequacy)

2. 资产质量(Asset Quality)

3. 管理 (Management)

4. 盈利性(Earnings)

5. 流动性(Liquidity)

6. 市场风险敏感度(Sensitivity to Market Risk)

## 骆驼评级的作用

1. 为全面评价一家银行的经营管理状况提供了统一的标准

2. 为同一银行在不同时期的经营表现比较提供了工具
