---
title: "第六章  企业贷款及其管理"
author: "Qiufei"
date: "2/6/2017"
output:
  ioslides_presentation: 
    logo: wanli.png
    widescreen: true
    keep_md: yes
---



# 第六章 企业贷款及其管理 #

## 一个例子：中国企业的炒矿，炒房地产 ##

## 银行发放贷款应考虑的因素 ##

1. 机会评估：确认借款人是不是可以成为银行的客户。
2. 初步分析：确认企业的借款原因。
3. 还款来源分析：风险与现金流分析。

## 企业贷款理由的分析 ##

1. 销售增长导致的借款
2. 营业周期减慢导致的借款
3. 固定资产投资导致的借款
4. 其他理由导致的借款

## 销售增长导致的借款 ##

1. 短期季节性销售增长。
此时银行需要检查企业至少一年的企业月销售额情况，以确定是否存在销售旺季。

2. 长期销售增长。
此时银行需要检查企业近几年的销售增长情况，一般年销售增长率超过10%则意味着企业需要额外的资金。

## 营业周期减慢导致的借款 ##

* 企业存货周转减慢和应收帐款回收减慢，都会导致企业流动性资金减少，从而带来贷款的需求。

* 此时银行需要检查企业最近的应收帐款账龄分析表。

## 固定投资投资导致的借款 ##

* 固定资产投资是一种经营扩张行为，对于此类贷款，银行首先要分析其扩张的合理性。

* 对于固定资产更新的需求，银行可以通过固定资产利用率（已提折旧累计额／折旧固定资产总额）和固定资产存续期（固定资产净额／折旧费）来测算贷款的额度和期限。

* 对于新增固定资产需求，银行可以通过销售／固定资产的占比来分析新增投资的合理性。

## 其他原因导致的贷款 ##

1. 资产增长导致的借款。
+ 投资账户
+ 递延费用
+ 预付费用
+ 无形资产

2. 债务重组导致的借款。
确认借款是目的是替换现存债务，还是支付费用。

3. 一次性或意外费用支出导致的借款。
银行要分析企业为什么无力支付这些支出。

## 影响企业还款能力的因素 ##

1. 财务状况
2. 现金流状况
3. 信用支持情况（担保保证情况）
4. 非财务因素

## 借款企业的财务状况分析 ##

1. 损益表分析：主要是为了确定利润增长情况。
2. 资产负债表分析：主要是为了确定效率和风险水平。



## 为什么还要做现金流量分析？ ##

* 净利润不是现金，只是会计报表上的数字反映。
* 只有现金才能偿还贷款。

## 借款企业现金流分析 ##

> 现金净流量 = 经营活动中的现金净流量 + 投资活动中的现金净流量 + 融资活动中的现金净流量


## 贷款担保的种类 ##

1. 抵押／质押
2. 保证
3. 附属合同

## 抵押/质押 ##

* 抵押不转移占有权，质押转移占有权。

* 一般是流通性好，质量较好的资产。

* 是银行的第二还款来源。

## 保证 ##

* 保证人为企业贷款协议提供担保，若企业无力偿还银行贷款，由担保人承担债务。

* 担保人一般是企业的合伙人、股东或高管。或者是母公司为子公司提供担保。

## 附属合同 ##

* 借款企业其他债权人签署的，同意对银行贷款负第二责任的的协议。

* 为银行提供对其他债权人的优先债务清偿权。

## 借款企业的非财务因素分析 ##

1. 行业风险分析：行业周期分析
2. 经营情况分析：产品竞争力与客户群体分析。
3. 管理情况分析：公司治理情况分析
4. 借款人的还款意愿。


## 企业贷款的定价 ##

1. 成本加成贷款定价法
2. 价格领导模型定价法
3. 成本-收益定价法

## 成本加成贷款定价 ##

* 前提：银行能够精确计算成本，并将其分摊到各项业务中。

> 贷款利率 = 筹集资金的边际成本 + 银行的其他经营成本 + 预计违约风险的补偿费用 + 银行预期的利润

## 价格领导模型定价法 ##

各项业务成本准确计量的困难导致了一种基准利率的加成定价法：

> 贷款利率 = 优惠利率 + 违约风险贴水 + 期限风险贴水

优惠利率是本行对信誉登记最好的大公司提供短期流动资金贷款的最低利率。

## 成本-收益定价法 ##

* 实际中的操作，是以单笔业务的收益来确定的。

* 银行除了收益利息费用之外，还可以以其他手段来提高收益。比如：
- 贷款转存，
- 集中办理结算业务等

