---
title: "讨论四：住房抵押贷款证券化是否应该由商业银行来做"
author: "邱飞"
date: "万里学院"
output:
  revealjs::revealjs_presentation:
    theme: sky
    reveal_options:
      slideNumber: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 住房目标是一个经济目标，还是社会目标？

- 如果是经济目标，市场有能力满足

- 如果是社会目标，不应该由纯经济的机构去做

## 风险谁来承担？

- 风险不会消失

- 所以，我们要明确风险的承担者

## 如果住房所有权是个社会目标

- 如果住房所有权的普及是个社会目标，就应该由专门的机构来做这个事情

- 美国的房地美和房利美这两大机构就是专门用来帮助实现住房抵押贷款的机构

- 如果让互助保险的任务落到商业机构的肩头，这回带来激励的扭曲


## 商业银行经营模式的变化

- 从store business 到moving business

- 然而长期客户关系是控制信用风险的重要手段



## 房地美和房利美被商业机构带坏了

- 房地美和房利美起初只做高质量客户的房贷业务

- 但是，商业机构开始搞住房抵押债券的证券化后，也被迫与他们竞争，做次贷业务

## 资产证券化中评级公司的作用

- 资产证券化需要有评级机构对打包资产的质量进行评估

- 没有这个环节解决信息不对称问题，资产证券化只会造成信用风险的累计

## 本次危机中历史评级公司的表现

- “帮助”发型机构设计产品，以便于通过评级

- 一个例子：将某个资产池分为三段打包，虽然前两段资产的收益和风险情况可以评上A级，但是最末端的风险较高，难以获得A等评级。于是评级公司建议发行方再设计一个补偿条款，就是如果末端资产损失超过一定的比例，最高段资产收益要支付一定的收益给最末段资产。由于评价公司假定这个超过一定比例的概率比较低，所以不影响高端资产的评级，同时，犹豫低段资产有了一个风险补偿保障，它也能获得较高的评级。


## 评级机构的历史表现

- 1997东南亚金融危机中，在泰铢贬值的前几天，评级公司依然对泰铢维持高评级。

- 2000美国安然、世通公司破产中，评级公司同样没有发挥风险提示和发现的作用。

> “一些人对评级公司的糟糕保险表示惊讶，而我对他们的惊讶表示惊讶   ——stiglitz”

## 评级机构存在的问题

- 本次危机中存在的暴露出来的问题：评级机构是证券发行方付费的，这里就存在利益冲突问题。

> they may not understand risk, but they understand incentives.

- 核心的问题：银行贷款出了问题，由银行拨备和资本来承担损失；评级除了错，评级公司用什么来承担损失？

